#ifndef _SET_TELEKINESIS_H_
#define _SET_TELEKINESIS_H_ 1

#include "TEvent.h"
#include "TObject.h"
#include "Variant.h"

#include <string>
#include <map>

class ApplyTelekinesis : public TEvent{

    public:
        glm::vec3 target_velocity;
        //glm::vec3 target_angular_velocity;
        float max_acceleration ;
        float max_angular_speed;

        glm::quat new_orientation;


        ApplyTelekinesis();

        ApplyTelekinesis(int solid_id, glm::vec3 dv, float ma, glm::quat o, float mas);

        ~ApplyTelekinesis() override;

        // Serialize this event's data, so it can be efficiently moved between timelines
        std::map<std::string,Variant> serialize() const override;

        // Set this event to data generated by its serialize method
        void set(std::map<std::string,Variant>& serialized) override;

        // Runs the event
        // This is what you need to override to implement your application
        // To maintain causality run should only interact with dynamic data by using the privided methods:
        // get(id), getMutable(), addEvent, createObject, deleteObject, and getCollisions
        void run() override;

};
#endif // #ifndef _SET_TELEKINESIS_H_