#ifndef _APPLY_BALL_IMPULSE_H_
#define _APPLY_BALL_IMPULSE_H_ 1

#include "TEvent.h"
#include "TObject.h"
#include "Variant.h"

#include <string>
#include <map>


class ApplyBallImpulse : public TEvent{

    public:
        glm::vec3 impulse;

        ApplyBallImpulse();

        ApplyBallImpulse(int moving_object, glm::vec3 v);

        ~ApplyBallImpulse() override;

        // Serialize this event's data, so it can be efficiently moved between timelines
        std::map<std::string,Variant> serialize() const override;

        // Set this event to data generated by its serialize method
        void set(std::map<std::string,Variant>& serialized) override;

        // Runs the event
        // This is what you need to override to implement your application
        // To maintain causality run should only interact with dynamic data by using the privided methods:
        // get(id), getMutable(), addEvent, createObject, deleteObject, and getCollisions
        void run() override;

        
};
#endif // #ifndef _APPLY_BALL_IMPULSE_H_