#ifndef _MOVE_OBJECT_H_
#define _MOVE_OBJECT_H_ 1

#include "TEvent.h"
#include "TObject.h"
#include "Variant.h"

#include <string>
#include <map>


class MoveObject : public TEvent{

    public:

        MoveObject();

        MoveObject(int moving_object, double time_step);

        MoveObject(double time_step);

        ~MoveObject() override;

        // Serialize this event's data, so it can be efficiently moved between timelines
        std::map<std::string,Variant> serialize() const override;

        // Set this event to data generated by its serialize method
        void set(std::map<std::string,Variant>& serialized) override;

        // Runs the event
        // This is what you need to override to implement your application
        // To maintain causality run should only interact with dynamic data by using the privided methods:
        // get(id), getMutable(), addEvent, createObject, deleteObject, and getCollisions
        void run() override;

    private:
        double interval ;

        
};
#endif // #ifndef _MOVE_OBJECT_H_