#ifndef _SET_MESH_INSTANCE_H_
#define _SET_MESH_INSTANCE_H_ 1

#include "TEvent.h"
#include "TObject.h"
#include "Variant.h"

#include <string>
#include <map>


class SetMeshInstance : public TEvent{

    public:
        glm::vec3 new_position;
        float new_radius ;
        std::string new_mesh_name ;
        glm::mat4 new_pose;
        Variant new_bone_data;

        SetMeshInstance();

        SetMeshInstance(int mesh_id, glm::vec3 p, float r,const std::string& name, const glm::mat4& m, const Variant& bones);

        ~SetMeshInstance() override;

        // Serialize this event's data, so it can be efficiently moved between timelines
        std::map<std::string,Variant> serialize() const override;

        // Set this event to data generated by its serialize method
        void set(std::map<std::string,Variant>& serialized) override;

        // Runs the event
        // This is what you need to override to implement your application
        // To maintain causality run should only interact with dynamic data by using the privided methods:
        // get(id), getMutable(), addEvent, createObject, deleteObject, and getCollisions
        void run() override;

        
};
#endif // #ifndef _SET_MESH_INSTANCE_H_