#ifndef _TOBJECT_H_
#define _TOBJECT_H_ 1

#include "Variant.h"

class Timeline{

    public:

        vec3 position;
        float radius;
        double write_time ;

        // pointer to user defined function to generated typed TObjects for their app
        static TObject(*generateTypedTObject)(Variant& serialized) ; 

        // Serialize this object, so it can be efficiently moved between timelines
        virtual std::map<std::string,Variant> serialize();

        // Set this object to data generated by its serialize method
        virtual void set(std::map<std::string,Variant>& serialized);

        // Override this to provide an efficient deep copy of this object
        // If not overridden serialize and set will be used to copy your object (which will be inefficent)
        TObject deepCopy();

        // Override this function to provide logic for interpolation after rollback or extrapolation for slowly updating objects
        // If not overridden getObserved returns the raw value of the object
        TObject getObserved(const TObject& last_observed);


        // Data and functions below this point are used for maintining the timeline continuity
        vector<std::pair<*TEvent, double>> readers ; // events that have read this object instant and when    
};
#endif // #ifndef _TOBJECT_H_